var biblioteca = [{"Titulo":"Memórias Póstumas de Brás Cubas",
                   "Autor":"Machado de Assis",
                   "Edicao":150,
                   "AnoPublic":2001,
                   "Editora":"Oxford University Press",
                   "LocalPublic":"Brasil",
                   "Codigo":03,
                   "Assunto":"Romance, Ficção",
                   "Classificacao":09
                },
                {"Titulo":"O Cortiço",
                   "Autor":" Aluísio Azevedo",
                   "Edicao":64,
                   "AnoPublic":1890,
                   "Editora":"B. L. Garnier",
                   "LocalPublic":"Brasil",
                   "Codigo":06,
                   "Assunto":"Romance, Ficção, Literatura do naturalismo",
                   "Classificacao":10
                },
                {"Titulo":"Dom Casmurro",
                   "Autor":"Machado de Assis",
                   "Edicao":1,
                   "AnoPublic":1899,
                   "Editora":"Livraria Garnier",
                   "LocalPublic":"Brasil",
                   "Codigo":08,
                   "Assunto":"Romance, Ficção, Memórias, Realismo Literário",
                   "Classificacao":08
                },
                {"Titulo":"Meu Pé de Laranja Lima",
                   "Autor":"José Mauro de Vasconcelos",
                   "Edicao":60,
                   "AnoPublic":1968,
                   "Editora":"Editora Melhoramentos",
                   "LocalPublic":"Brasil",
                   "Codigo":01,
                   "Assunto":"Ficção",
                   "Classificacao":07
                },
                {"Titulo":"Vidas Secas",
                   "Autor":"Graciliano Ramos",
                   "Edicao":140,
                   "AnoPublic":1938,
                   "Editora":"N/A",
                   "LocalPublic":"Brasil",
                   "Codigo":01,
                   "Assunto":"Romance, Ficção",
                   "Classificacao":6
                },
            ];//Exercicio feito em grupo Augusto de Souza, Augusto dos Santos e Brandon Carlos